services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - CSRF_KEY
      - CSRF_SECURE
      - GOOSE_DBSTRING
      - GOOSE_DRIVER
      - IMAGES_ALLOWED_EXTENSIONS
      - IMAGES_ALLOWED_TYPES
      - IMAGES_DIR
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - PSQL_HOST
      - PSQL_PORT
      - PSQL_SSLMODE
      - SERVER_PUBLIC_ADDRESS
      - SERVER_PORT
      - SMTP_DEFAULT_SENDER
      - SMTP_HOST
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USERNAME
    volumes:
      - ./images:/app/images
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy
    restart: always
    environment:
      - SERVER_PORT
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
