services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - CSRF_KEY
      - CSRF_SECURE
      - GOOSE_DBSTRING
      - GOOSE_DRIVER
      - IMAGES_ALLOWED_EXTENSIONS
      - IMAGES_ALLOWED_TYPES
      - IMAGES_DIR
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - PSQL_HOST
      - PSQL_PORT
      - PSQL_SSLMODE
      - SERVER_PUBLIC_ADDRESS
      - SERVER_PORT
      - SMTP_DEFAULT_SENDER
      - SMTP_HOST
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USERNAME
    volumes:
      - ${IMAGES_DIR_HOST}:/app/images
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy
    restart: always
    environment:
      - SERVER_PORT
      - CADDY_SITE_ADDRESS
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

# db override to keep the db data in the PSQL_DATA_HOST directory
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${PSQL_DATA_HOST}:/var/lib/postgresql/data/pgdata
